import { ConsumerProduct, ConsumerOrder, ConsumerTransactionRecord } from './ConsumerTypes';

export const CONSUMER_PRODUCTS: ConsumerProduct[] = [
  // FEATURED: Tomatoes
  {
    id: 'prod-tomato',
    name: 'Tomatoes',
    emoji: '🍅',
    category: 'Vegetables',
    variety: 'Abhinav Vine-Ripened Hybrid',
    kisanDirectPricePerKg: 27,
    traditionalRetailPricePerKg: 32,
    farmerSharePerKg: 23,
    transportSharePerKg: 3,
    platformSharePerKg: 1,
    sourceNetwork: 'Local Farmer Network',
    sourceLocation: 'Junnar & Khed Farmer Producer Org, Pune',
    distanceKm: 34,
    harvestTimeAgo: 'Harvested 4 hours ago',
    freshnessScore: 98,
    availableKg: 850,
    unit: 'kg',
    grade: 'Grade A',
    imagePlaceholderColor: 'from-rose-500/20 to-red-600/10',
    description: 'Crisp, naturally red farmgate tomatoes directly harvested from local Maharashtra farmer clusters. Zero ripening agents used.',
    featured: true,
  },
  // Vegetables
  {
    id: 'prod-potato',
    name: 'Potatoes',
    emoji: '🥔',
    category: 'Vegetables',
    variety: 'Kufri Jyoti Gold',
    kisanDirectPricePerKg: 22,
    traditionalRetailPricePerKg: 26,
    farmerSharePerKg: 18.5,
    transportSharePerKg: 2.5,
    platformSharePerKg: 1,
    sourceNetwork: 'Local Farmer Network',
    sourceLocation: 'Manchar Potato Growers Collective, Pune',
    distanceKm: 42,
    harvestTimeAgo: 'Harvested yesterday evening',
    freshnessScore: 96,
    availableKg: 1200,
    unit: 'kg',
    grade: 'Grade A',
    imagePlaceholderColor: 'from-amber-600/20 to-yellow-700/10',
    description: 'Firm, thin-skinned potatoes ideal for roasting, curries, and chips with high dry matter content.',
  },
  {
    id: 'prod-onion',
    name: 'Onions',
    emoji: '🧅',
    category: 'Vegetables',
    variety: 'Nashik Red Premium',
    kisanDirectPricePerKg: 30,
    traditionalRetailPricePerKg: 36,
    farmerSharePerKg: 25.5,
    transportSharePerKg: 3.5,
    platformSharePerKg: 1,
    sourceNetwork: 'Local Farmer Network',
    sourceLocation: 'Lasalgaon Onion Farmers Cluster, Nashik',
    distanceKm: 145,
    harvestTimeAgo: 'Harvested 12 hours ago',
    freshnessScore: 95,
    availableKg: 2400,
    unit: 'kg',
    grade: 'Grade A',
    imagePlaceholderColor: 'from-purple-600/20 to-fuchsia-700/10',
    description: 'Pungent, dense-layered red onions with prolonged natural kitchen shelf-life.',
  },
  {
    id: 'prod-carrot',
    name: 'Carrots',
    emoji: '🥕',
    category: 'Vegetables',
    variety: 'Ooty Dark Red Tender',
    kisanDirectPricePerKg: 38,
    traditionalRetailPricePerKg: 46,
    farmerSharePerKg: 32,
    transportSharePerKg: 4.5,
    platformSharePerKg: 1.5,
    sourceNetwork: 'Local Farmer Network',
    sourceLocation: 'Talegaon Agro Producer Coop',
    distanceKm: 28,
    harvestTimeAgo: 'Harvested 6 hours ago',
    freshnessScore: 97,
    availableKg: 620,
    unit: 'kg',
    grade: 'Grade A',
    imagePlaceholderColor: 'from-orange-500/20 to-amber-600/10',
    description: 'Sweet, juicy crunchy carrots washed with pure mountain spring water at the farmgate.',
  },
  {
    id: 'prod-leafy',
    name: 'Leafy Vegetables',
    emoji: '🥬',
    category: 'Vegetables',
    variety: 'Fresh Green Palak (Spinach)',
    kisanDirectPricePerKg: 24,
    traditionalRetailPricePerKg: 30,
    farmerSharePerKg: 20,
    transportSharePerKg: 3,
    platformSharePerKg: 1,
    sourceNetwork: 'Local Farmer Network',
    sourceLocation: 'Alandi Hydro & Soil Farms',
    distanceKm: 18,
    harvestTimeAgo: 'Harvested 3 hours ago',
    freshnessScore: 99,
    availableKg: 350,
    unit: 'bunch',
    grade: 'Organic Certified',
    imagePlaceholderColor: 'from-emerald-500/20 to-green-700/10',
    description: 'Tender, nutrient-rich pesticide-free green spinach harvested before sunrise for maximum vitamin retention.',
  },

  // Fruits
  {
    id: 'prod-apple',
    name: 'Apples',
    emoji: '🍎',
    category: 'Fruits',
    variety: 'Kinnaur Royal Crisp',
    kisanDirectPricePerKg: 110,
    traditionalRetailPricePerKg: 135,
    farmerSharePerKg: 92,
    transportSharePerKg: 12,
    platformSharePerKg: 6,
    sourceNetwork: 'Local Farmer Network',
    sourceLocation: 'Himachal Orchardists Direct Link',
    distanceKm: 450,
    harvestTimeAgo: 'Cold Chain Arrived Today',
    freshnessScore: 94,
    availableKg: 780,
    unit: 'kg',
    grade: 'Grade A+',
    imagePlaceholderColor: 'from-red-500/20 to-rose-700/10',
    description: 'High-altitude aromatic apples with natural crunch, zero synthetic wax coating.',
  },
  {
    id: 'prod-banana',
    name: 'Bananas',
    emoji: '🍌',
    category: 'Fruits',
    variety: 'Grand Naine Robusta',
    kisanDirectPricePerKg: 36,
    traditionalRetailPricePerKg: 48,
    farmerSharePerKg: 29,
    transportSharePerKg: 5,
    platformSharePerKg: 2,
    sourceNetwork: 'Local Farmer Network',
    sourceLocation: 'Jalgaon Banana Farmer Producer Group',
    distanceKm: 210,
    harvestTimeAgo: 'Naturally Ethylene Ripened',
    freshnessScore: 96,
    availableKg: 950,
    unit: 'dozen',
    grade: 'Grade A',
    imagePlaceholderColor: 'from-yellow-400/20 to-amber-500/10',
    description: 'Sweet, potassium-dense bananas naturally tree-ripened without chemical calcium carbide.',
  },
  {
    id: 'prod-mango',
    name: 'Mangoes',
    emoji: '🥭',
    category: 'Fruits',
    variety: 'Devgad Alphonso (Hapus)',
    kisanDirectPricePerKg: 380,
    traditionalRetailPricePerKg: 460,
    farmerSharePerKg: 320,
    transportSharePerKg: 42,
    platformSharePerKg: 18,
    sourceNetwork: 'Local Farmer Network',
    sourceLocation: 'Konkan Coast GI Certified Groves',
    distanceKm: 180,
    harvestTimeAgo: 'Harvested yesterday',
    freshnessScore: 99,
    availableKg: 420,
    unit: 'dozen',
    grade: 'Organic Certified',
    imagePlaceholderColor: 'from-amber-400/20 to-orange-600/10',
    description: 'GI-tagged authentic Devgad Alphonso mangoes with rich saffron aroma and velvety golden pulp.',
  },
  {
    id: 'prod-orange',
    name: 'Oranges',
    emoji: '🍊',
    category: 'Fruits',
    variety: 'Nagpur Sweet Mandarin',
    kisanDirectPricePerKg: 65,
    traditionalRetailPricePerKg: 82,
    farmerSharePerKg: 54,
    transportSharePerKg: 8,
    platformSharePerKg: 3,
    sourceNetwork: 'Local Farmer Network',
    sourceLocation: 'Vidarbha Citrus Growers Collective',
    distanceKm: 320,
    harvestTimeAgo: 'Harvested 18 hours ago',
    freshnessScore: 95,
    availableKg: 880,
    unit: 'kg',
    grade: 'Grade A',
    imagePlaceholderColor: 'from-orange-400/20 to-amber-600/10',
    description: 'Juicy, seed-minimal sweet mandarins rich in vitamin C and natural citrus antioxidants.',
  },
];

export const INITIAL_CONSUMER_ORDER: ConsumerOrder = {
  id: 'order-10243',
  orderNumber: '#10243',
  txHash: '0x8f2a9c14e712ba6d9410ef39b207ca91834fd2a7',
  productName: 'Tomatoes',
  emoji: '🍅',
  quantityKg: 5,
  pricePerKg: 27,
  subtotal: 135,
  transportFee: 15,
  platformFee: 0,
  totalAmount: 150,
  farmerNetwork: 'Local Farmer Network (Junnar Cluster)',
  orderTimestamp: 'Today, 09:15 AM',
  expectedDelivery: 'Today, 6:30 PM',
  statusStep: 'BEING_PREPARED',
  paymentMethod: 'UPI (Google Pay)',
  paymentStatus: 'COMPLETED',
  deliveryAddress: 'Flat 402, Green Meadows, Baner, Pune - 411045',
};

export const INITIAL_CONSUMER_TRANSACTIONS: ConsumerTransactionRecord[] = [
  {
    txId: 'TX10243',
    orderNumber: '#10243',
    productTitle: 'Tomatoes — 5 kg',
    emoji: '🍅',
    quantityFormatted: '5 kg',
    farmerNetwork: 'Local Farmer Network',
    productValue: 135,
    transportationFee: 15,
    platformFee: 5,
    totalPaid: 155,
    savingsVsRetail: 25,
    paymentMethod: 'UPI Instant Settlement',
    status: 'COMPLETED',
    timestamp: '2026-09-02 09:15:22 IST',
    blockHash: '0x8f2a9c14e712ba6d9410ef39b207ca91834fd2a7e4b9c10d32e91a0b3c4d5e6f',
    securityCipher: 'AES-256-GCM + SHA-256 Chained',
    auditVerified: true,
  },
  {
    txId: 'TX10238',
    orderNumber: '#10238',
    productTitle: 'Potatoes & Onions Combo — 10 kg',
    emoji: '🥔',
    quantityFormatted: '10 kg',
    farmerNetwork: 'Manchar & Lasalgaon Network',
    productValue: 260,
    transportationFee: 20,
    platformFee: 5,
    totalPaid: 285,
    savingsVsRetail: 55,
    paymentMethod: 'Digital Escrow Card',
    status: 'COMPLETED',
    timestamp: '2026-08-30 14:22:10 IST',
    blockHash: '0x9a3b0d25f823cb7e0521fe40c318db02945fe3b8f5ca01e43f012b1c4d5e6f7a',
    securityCipher: 'AES-256-GCM + OTP 2FA Verified',
    auditVerified: true,
  },
  {
    txId: 'TX10219',
    orderNumber: '#10219',
    productTitle: 'Devgad Alphonso Mangoes — 2 Dozen',
    emoji: '🥭',
    quantityFormatted: '2 Dozen',
    farmerNetwork: 'Konkan Coast GI Collective',
    productValue: 760,
    transportationFee: 40,
    platformFee: 10,
    totalPaid: 810,
    savingsVsRetail: 160,
    paymentMethod: 'UPI Auto-Pay',
    status: 'COMPLETED',
    timestamp: '2026-08-27 18:40:05 IST',
    blockHash: '0xab4c1e36a934dc8f1632af51d429ec13056af4c9a6db12f54a123c2d5e6f7a8b',
    securityCipher: 'AES-256-GCM + Zero Knowledge Ledger',
    auditVerified: true,
  },
];
