import { 
  GovernmentKPIs, 
  DistrictData, 
  HotspotAlert, 
  ProduceMovementRecord, 
  MarketPriceRecord, 
  GovernmentSecurityAlert, 
  TransactionSecurityStats, 
  FraudFlagRecord, 
  TransactionAuditRecord, 
  ReportConfig,
  FarmerIncomeMetric,
  ConsumerPriceMetric,
  TimeframeOption
} from './GovernmentTypes';

export const TIMEFRAME_KPIS: Record<TimeframeOption, GovernmentKPIs> = {
  'Today': {
    farmersOnboarded: 12482,
    farmersTrendPct: 2.1,
    farmersTrendDir: 'up',
    activeBuyers: 3821,
    buyersTrendPct: 4.3,
    buyersTrendDir: 'up',
    transactionsCount: 1420,
    transactionsTrendPct: 5.2,
    transactionsTrendDir: 'up',
    avgFarmerIncomePct: 18.4,
    farmerIncomeTrendDir: 'up',
    avgConsumerPricePct: 9.2,
    consumerPriceTrendDir: 'down',
    intermediariesEliminated: 2.3,
    intermediariesTrendDir: 'stable',
    produceTradedTonnes: 54.8,
    produceTrendPct: 3.8,
    produceTrendDir: 'up',
  },
  '7 Days': {
    farmersOnboarded: 12482,
    farmersTrendPct: 6.8,
    farmersTrendDir: 'up',
    activeBuyers: 3821,
    buyersTrendPct: 8.5,
    buyersTrendDir: 'up',
    transactionsCount: 9840,
    transactionsTrendPct: 11.2,
    transactionsTrendDir: 'up',
    avgFarmerIncomePct: 18.4,
    farmerIncomeTrendDir: 'up',
    avgConsumerPricePct: 9.2,
    consumerPriceTrendDir: 'down',
    intermediariesEliminated: 2.3,
    intermediariesTrendDir: 'stable',
    produceTradedTonnes: 342.0,
    produceTrendPct: 7.9,
    produceTrendDir: 'up',
  },
  '30 Days': {
    farmersOnboarded: 12482,
    farmersTrendPct: 14.2,
    farmersTrendDir: 'up',
    activeBuyers: 3821,
    buyersTrendPct: 16.7,
    buyersTrendDir: 'up',
    transactionsCount: 48293,
    transactionsTrendPct: 19.4,
    transactionsTrendDir: 'up',
    avgFarmerIncomePct: 18.4,
    farmerIncomeTrendDir: 'up',
    avgConsumerPricePct: 9.2,
    consumerPriceTrendDir: 'down',
    intermediariesEliminated: 2.3,
    intermediariesTrendDir: 'stable',
    produceTradedTonnes: 1284.0,
    produceTrendPct: 15.6,
    produceTrendDir: 'up',
  },
  '6 Months': {
    farmersOnboarded: 10840,
    farmersTrendPct: 42.5,
    farmersTrendDir: 'up',
    activeBuyers: 2950,
    buyersTrendPct: 51.0,
    buyersTrendDir: 'up',
    transactionsCount: 241500,
    transactionsTrendPct: 48.0,
    transactionsTrendDir: 'up',
    avgFarmerIncomePct: 17.8,
    farmerIncomeTrendDir: 'up',
    avgConsumerPricePct: 8.9,
    consumerPriceTrendDir: 'down',
    intermediariesEliminated: 2.2,
    intermediariesTrendDir: 'stable',
    produceTradedTonnes: 6420.0,
    produceTrendPct: 39.4,
    produceTrendDir: 'up',
  },
  '1 Year': {
    farmersOnboarded: 7920,
    farmersTrendPct: 88.0,
    farmersTrendDir: 'up',
    activeBuyers: 1840,
    buyersTrendPct: 112.5,
    buyersTrendDir: 'up',
    transactionsCount: 412000,
    transactionsTrendPct: 104.0,
    transactionsTrendDir: 'up',
    avgFarmerIncomePct: 18.1,
    farmerIncomeTrendDir: 'up',
    avgConsumerPricePct: 9.1,
    consumerPriceTrendDir: 'down',
    intermediariesEliminated: 2.3,
    intermediariesTrendDir: 'stable',
    produceTradedTonnes: 11840.0,
    produceTrendPct: 92.0,
    produceTrendDir: 'up',
  },
};

export const FARMER_INCOME_DATA: FarmerIncomeMetric[] = [
  {
    commodity: 'Tomato (Overall)',
    traditionalIncome: 8500,
    kisanDirectIncome: 10065,
    percentageIncrease: 18.4,
    farmerSharePctTraditional: 43.8,
    farmerSharePctKisanDirect: 85.2,
  },
  {
    commodity: 'Potato (Kufri)',
    traditionalIncome: 7200,
    kisanDirectIncome: 8490,
    percentageIncrease: 17.9,
    farmerSharePctTraditional: 46.0,
    farmerSharePctKisanDirect: 84.0,
  },
  {
    commodity: 'Nashik Red Onion',
    traditionalIncome: 11400,
    kisanDirectIncome: 13620,
    percentageIncrease: 19.5,
    farmerSharePctTraditional: 42.5,
    farmerSharePctKisanDirect: 86.0,
  },
  {
    commodity: 'Carrot (Gajar)',
    traditionalIncome: 9100,
    kisanDirectIncome: 10650,
    percentageIncrease: 17.0,
    farmerSharePctTraditional: 45.0,
    farmerSharePctKisanDirect: 83.5,
  },
  {
    commodity: 'Cauliflower (Gobi)',
    traditionalIncome: 6800,
    kisanDirectIncome: 8120,
    percentageIncrease: 19.4,
    farmerSharePctTraditional: 41.0,
    farmerSharePctKisanDirect: 85.0,
  },
];

export const CONSUMER_PRICE_DATA: ConsumerPriceMetric[] = [
  {
    commodity: 'Tomato',
    traditionalPricePerKg: 32,
    kisanDirectPricePerKg: 29,
    savingAmount: 3,
    savingPercentage: 9.38,
  },
  {
    commodity: 'Potato',
    traditionalPricePerKg: 24,
    kisanDirectPricePerKg: 21.5,
    savingAmount: 2.5,
    savingPercentage: 10.42,
  },
  {
    commodity: 'Onion',
    traditionalPricePerKg: 38,
    kisanDirectPricePerKg: 34.5,
    savingAmount: 3.5,
    savingPercentage: 9.21,
  },
  {
    commodity: 'Carrot',
    traditionalPricePerKg: 42,
    kisanDirectPricePerKg: 38,
    savingAmount: 4,
    savingPercentage: 9.52,
  },
  {
    commodity: 'Cauliflower',
    traditionalPricePerKg: 28,
    kisanDirectPricePerKg: 25.5,
    savingAmount: 2.5,
    savingPercentage: 8.93,
  },
];

export const DELHI_NCR_DISTRICTS: DistrictData[] = [
  {
    id: 'dist-delhi',
    name: 'Delhi',
    state: 'National Capital Territory',
    coordinates: { x: 48, y: 46, lat: 28.6139, lng: 77.2090 },
    densityDots: '●●●●●',
    farmersCount: 4823,
    activeBuyersCount: 1840,
    totalTransactions: 18293,
    incomeImpactPct: 21.4,
    produceAvailable: [
      { name: 'Tomato', variety: 'Roma / Hybrid', tonnes: 180, demandLevel: 'HIGH', avgPrice: 24, priceTrend: '↑ 21.0%', supplyStatus: 'SHORTAGE' },
      { name: 'Potato', variety: 'Kufri Jyoti', tonnes: 120, demandLevel: 'MEDIUM', avgPrice: 21, priceTrend: '→ 0.0%', supplyStatus: 'BALANCED' },
      { name: 'Onion', variety: 'Nashik Red', tonnes: 95, demandLevel: 'HIGH', avgPrice: 35, priceTrend: '↑ 14.5%', supplyStatus: 'SHORTAGE' },
      { name: 'Green Vegetables', variety: 'Spinach/Coriander', tonnes: 60, demandLevel: 'HIGH', avgPrice: 40, priceTrend: '↑ 12.0%', supplyStatus: 'SHORTAGE' },
    ],
    primaryProduce: 'Urban Consumption Hub',
    availableTonnes: 455,
    demandTrendPct: 21.0,
    averageTomatoPrice: 24,
    logisticsStatus: 'OPTIMAL',
    supplyScore: 42,
    demandScore: 98,
    priceIndex: 114,
    transactionDensity: 142,
  },
  {
    id: 'dist-noida',
    name: 'Noida',
    state: 'Uttar Pradesh (Gautam Buddha Nagar)',
    coordinates: { x: 62, y: 58, lat: 28.5355, lng: 77.3910 },
    densityDots: '●●●●',
    farmersCount: 2843,
    activeBuyersCount: 712,
    totalTransactions: 10812,
    incomeImpactPct: 17.8,
    produceAvailable: [
      { name: 'Tomato', variety: 'Heirloom / Local', tonnes: 340, demandLevel: 'HIGH', avgPrice: 22, priceTrend: '↑ 14.2%', supplyStatus: 'SURPLUS' },
      { name: 'Potato', variety: 'Kufri Chandramukhi', tonnes: 210, demandLevel: 'MEDIUM', avgPrice: 18, priceTrend: '→ 0.5%', supplyStatus: 'SURPLUS' },
      { name: 'Onion', variety: 'Pusa Red', tonnes: 180, demandLevel: 'LOW', avgPrice: 26, priceTrend: '↓ 4.2%', supplyStatus: 'BALANCED' },
      { name: 'Cauliflower', variety: 'Early Kunwari', tonnes: 90, demandLevel: 'MEDIUM', avgPrice: 24, priceTrend: '↑ 3.2%', supplyStatus: 'BALANCED' },
    ],
    primaryProduce: 'Tomato (340 T) & Potato (210 T)',
    availableTonnes: 820,
    demandTrendPct: 14.2,
    averageTomatoPrice: 22,
    logisticsStatus: 'OPTIMAL',
    supplyScore: 89,
    demandScore: 74,
    priceIndex: 96,
    transactionDensity: 94,
  },
  {
    id: 'dist-ghaziabad',
    name: 'Ghaziabad',
    state: 'Uttar Pradesh',
    coordinates: { x: 65, y: 38, lat: 28.6692, lng: 77.4538 },
    densityDots: '●●●',
    farmersCount: 2103,
    activeBuyersCount: 540,
    totalTransactions: 8421,
    incomeImpactPct: 16.2,
    produceAvailable: [
      { name: 'Tomato', variety: 'Desi Red', tonnes: 160, demandLevel: 'HIGH', avgPrice: 23, priceTrend: '↑ 11.0%', supplyStatus: 'BALANCED' },
      { name: 'Potato', variety: 'Sugar Free White', tonnes: 140, demandLevel: 'LOW', avgPrice: 19, priceTrend: '↓ 1.5%', supplyStatus: 'SURPLUS' },
      { name: 'Onion', variety: 'Garhwa Red', tonnes: 70, demandLevel: 'HIGH', avgPrice: 36, priceTrend: '↑ 16.0%', supplyStatus: 'SHORTAGE' },
      { name: 'Carrot', variety: 'Pusa Kesar', tonnes: 110, demandLevel: 'MEDIUM', avgPrice: 30, priceTrend: '↑ 4.1%', supplyStatus: 'BALANCED' },
    ],
    primaryProduce: 'Mixed Vegetables & Aggregation Hub',
    availableTonnes: 480,
    demandTrendPct: 11.5,
    averageTomatoPrice: 23,
    logisticsStatus: 'MODERATE_CONGESTION',
    supplyScore: 68,
    demandScore: 82,
    priceIndex: 104,
    transactionDensity: 76,
  },
  {
    id: 'dist-meerut',
    name: 'Meerut',
    state: 'Uttar Pradesh',
    coordinates: { x: 75, y: 22, lat: 28.9845, lng: 77.7064 },
    densityDots: '●●',
    farmersCount: 1712,
    activeBuyersCount: 390,
    totalTransactions: 6238,
    incomeImpactPct: 14.9,
    produceAvailable: [
      { name: 'Tomato', variety: 'Polyhouse Cherry/Standard', tonnes: 110, demandLevel: 'MEDIUM', avgPrice: 21, priceTrend: '→ 0.0%', supplyStatus: 'BALANCED' },
      { name: 'Sugarcane & Jaggery', variety: 'CO-0238 Organic', tonnes: 420, demandLevel: 'HIGH', avgPrice: 45, priceTrend: '↑ 6.8%', supplyStatus: 'SURPLUS' },
      { name: 'Potato', variety: 'Kufri Bahar', tonnes: 190, demandLevel: 'LOW', avgPrice: 17, priceTrend: '↓ 2.0%', supplyStatus: 'SURPLUS' },
      { name: 'Wheat', variety: 'PBW 343', tonnes: 310, demandLevel: 'MEDIUM', avgPrice: 28, priceTrend: '→ 0.8%', supplyStatus: 'BALANCED' },
    ],
    primaryProduce: 'Sugarcane, Grains & Potato Hub',
    availableTonnes: 1030,
    demandTrendPct: 8.4,
    averageTomatoPrice: 21,
    logisticsStatus: 'OPTIMAL',
    supplyScore: 92,
    demandScore: 48,
    priceIndex: 91,
    transactionDensity: 52,
  },
  {
    id: 'dist-gurgaon',
    name: 'Gurgaon (Gurugram)',
    state: 'Haryana',
    coordinates: { x: 38, y: 64, lat: 28.4595, lng: 77.0266 },
    densityDots: '●●●●',
    farmersCount: 1940,
    activeBuyersCount: 1120,
    totalTransactions: 9820,
    incomeImpactPct: 19.2,
    produceAvailable: [
      { name: 'Tomato', variety: 'Hydroponic & Farmgate', tonnes: 90, demandLevel: 'HIGH', avgPrice: 26, priceTrend: '↑ 18.0%', supplyStatus: 'SHORTAGE' },
      { name: 'Mustard Greens & Seeds', variety: 'Pusa Bold', tonnes: 180, demandLevel: 'HIGH', avgPrice: 52, priceTrend: '↑ 8.5%', supplyStatus: 'BALANCED' },
      { name: 'Onion', variety: 'Kharif Special', tonnes: 60, demandLevel: 'HIGH', avgPrice: 37, priceTrend: '↑ 12.4%', supplyStatus: 'SHORTAGE' },
    ],
    primaryProduce: 'Premium Corporate & Retail Intake',
    availableTonnes: 330,
    demandTrendPct: 18.0,
    averageTomatoPrice: 26,
    logisticsStatus: 'OPTIMAL',
    supplyScore: 46,
    demandScore: 94,
    priceIndex: 118,
    transactionDensity: 118,
  },
  {
    id: 'dist-faridabad',
    name: 'Faridabad',
    state: 'Haryana',
    coordinates: { x: 52, y: 72, lat: 28.4089, lng: 77.3178 },
    densityDots: '●●●',
    farmersCount: 1350,
    activeBuyersCount: 460,
    totalTransactions: 5410,
    incomeImpactPct: 15.6,
    produceAvailable: [
      { name: 'Tomato', variety: 'Field Hybrid', tonnes: 140, demandLevel: 'MEDIUM', avgPrice: 22.5, priceTrend: '↑ 5.2%', supplyStatus: 'BALANCED' },
      { name: 'Potato', variety: 'Kufri Badshah', tonnes: 170, demandLevel: 'LOW', avgPrice: 18.5, priceTrend: '→ 0.0%', supplyStatus: 'SURPLUS' },
      { name: 'Radish & Turnip', variety: 'Japanese White', tonnes: 115, demandLevel: 'MEDIUM', avgPrice: 22, priceTrend: '↑ 3.0%', supplyStatus: 'BALANCED' },
    ],
    primaryProduce: 'Tubers & Winter Crops',
    availableTonnes: 425,
    demandTrendPct: 9.8,
    averageTomatoPrice: 22.5,
    logisticsStatus: 'OPTIMAL',
    supplyScore: 74,
    demandScore: 66,
    priceIndex: 98,
    transactionDensity: 65,
  },
  {
    id: 'dist-sonipat',
    name: 'Sonipat',
    state: 'Haryana',
    coordinates: { x: 42, y: 24, lat: 28.9931, lng: 77.0151 },
    densityDots: '●●',
    farmersCount: 1220,
    activeBuyersCount: 310,
    totalTransactions: 4220,
    incomeImpactPct: 16.4,
    produceAvailable: [
      { name: 'Tomato', variety: 'Polyhouse Grade A', tonnes: 210, demandLevel: 'HIGH', avgPrice: 21, priceTrend: '↑ 7.4%', supplyStatus: 'SURPLUS' },
      { name: 'Button Mushroom', variety: 'Commercial Pack', tonnes: 85, demandLevel: 'HIGH', avgPrice: 110, priceTrend: '↑ 9.0%', supplyStatus: 'SURPLUS' },
      { name: 'Baby Corn', variety: 'Pusa Hybrid Baby', tonnes: 95, demandLevel: 'HIGH', avgPrice: 65, priceTrend: '↑ 11.2%', supplyStatus: 'SURPLUS' },
    ],
    primaryProduce: 'Mushroom, Baby Corn & Polyhouse Tomato Hub',
    availableTonnes: 390,
    demandTrendPct: 12.1,
    averageTomatoPrice: 21,
    logisticsStatus: 'BOTTLENECK_ALERT',
    supplyScore: 94,
    demandScore: 52,
    priceIndex: 93,
    transactionDensity: 48,
  },
];

export const HOTSPOT_ALERTS: HotspotAlert[] = [
  {
    id: 'hotspot-1',
    type: 'HIGH_DEMAND',
    badgeColor: 'red',
    district: 'Delhi (NCT)',
    commodity: 'Tomatoes',
    metricLabel: 'Demand ↑ 21%',
    recommendation: 'Consider redirecting surplus tomato supply from Noida and Sonipat packhouses toward Delhi demand centers (Azadpur, Okhla & Ghazipur retail hubs).',
    severity: 'CRITICAL',
    timestamp: '12 mins ago',
  },
  {
    id: 'hotspot-2',
    type: 'SUPPLY_SURPLUS',
    badgeColor: 'amber',
    district: 'Noida (GB Nagar)',
    commodity: 'Potatoes (Kufri Chandramukhi)',
    metricLabel: 'Supply ↑ 18%',
    recommendation: 'Activate dynamic aggregation dispatch to cold storage reserves and route 120 tonnes to central NCR processing units to prevent farmgate distress selling.',
    severity: 'WARNING',
    timestamp: '28 mins ago',
  },
  {
    id: 'hotspot-3',
    type: 'POTENTIAL_SHORTAGE',
    badgeColor: 'yellow',
    district: 'Ghaziabad',
    commodity: 'Onions (Nashik Red)',
    metricLabel: 'Demand > Supply (Shortage 42 T)',
    recommendation: 'Fast-track cold-chain rake arrival from Nashik rail freight corridor into Ghaziabad logistics yard to buffer 16% price escalation.',
    severity: 'WARNING',
    timestamp: '45 mins ago',
  },
  {
    id: 'hotspot-4',
    type: 'HIGH_DEMAND',
    badgeColor: 'red',
    district: 'Gurgaon (Gurugram)',
    commodity: 'Hydroponic Salad Greens & Tomatoes',
    metricLabel: 'Demand ↑ 18%',
    recommendation: 'Prioritize FPO direct contracts from Sonipat polyhouse clusters with dedicated green corridor transport clearance.',
    severity: 'CRITICAL',
    timestamp: '1 hour ago',
  },
];

export const PRODUCE_MOVEMENTS: ProduceMovementRecord[] = [
  {
    id: 'mov-101',
    origin: 'Noida Central FPO Packhouse',
    destination: 'Delhi Urban Distribution Centers (Okhla / Connaught)',
    commodity: 'Tomatoes',
    quantityTonnes: 340,
    transportationCost: 48000,
    deliveryStatus: 'IN_TRANSIT',
    avgDeliveryTimeHrs: 1.8,
    vehicleCount: 14,
    coldChainCompliancePct: 98.4,
    hasBottleneck: false,
  },
  {
    id: 'mov-102',
    origin: 'Noida Agro Aggregator',
    destination: 'Ghaziabad & East Delhi Wholesale Hubs',
    commodity: 'Potatoes',
    quantityTonnes: 210,
    transportationCost: 32500,
    deliveryStatus: 'DISPATCHED',
    avgDeliveryTimeHrs: 2.4,
    vehicleCount: 9,
    coldChainCompliancePct: 94.2,
    hasBottleneck: false,
  },
  {
    id: 'mov-103',
    origin: 'Nashik Corridor Ingress (via Ghaziabad)',
    destination: 'Delhi Retail & Institutional Buyers',
    commodity: 'Onions',
    quantityTonnes: 180,
    transportationCost: 62000,
    deliveryStatus: 'BOTTLENECK_DELAY',
    avgDeliveryTimeHrs: 4.8,
    vehicleCount: 11,
    coldChainCompliancePct: 91.0,
    hasBottleneck: true,
    bottleneckReason: 'Heavy toll congestion at UP-Delhi border checkpost causing 2.4 hr transit lag.',
  },
  {
    id: 'mov-104',
    origin: 'Sonipat Agri-Tech Hub',
    destination: 'Gurgaon Corporate & Quick-Commerce Hubs',
    commodity: 'Mushroom & Baby Corn',
    quantityTonnes: 95,
    transportationCost: 24000,
    deliveryStatus: 'DELIVERED',
    avgDeliveryTimeHrs: 1.5,
    vehicleCount: 5,
    coldChainCompliancePct: 99.1,
    hasBottleneck: false,
  },
  {
    id: 'mov-105',
    origin: 'Meerut Aggregation Center',
    destination: 'Noida & South Delhi Mandis',
    commodity: 'Sugarcane Products & Grains',
    quantityTonnes: 240,
    transportationCost: 38000,
    deliveryStatus: 'IN_TRANSIT',
    avgDeliveryTimeHrs: 3.1,
    vehicleCount: 10,
    coldChainCompliancePct: 92.5,
    hasBottleneck: false,
  },
];

export const MARKET_PRICES_DATA: MarketPriceRecord[] = [
  {
    id: 'mp-tomato',
    product: 'Tomato',
    category: 'Vegetables',
    variety: 'Roma / Hybrid Grade A',
    avgPricePerKg: 22.0,
    traditionalRetailPricePerKg: 32.0,
    priceTrendPct: 8.4,
    trendDirection: 'up',
    demandLevel: 'HIGH',
    supplyLevel: 'ADEQUATE',
    dominantDistrict: 'Noida (Surplus) / Delhi (Demand)',
    anomalyDetected: false,
    lastUpdated: '02 Sep 2026, 17:45 IST',
  },
  {
    id: 'mp-potato',
    product: 'Potato',
    category: 'Tubers',
    variety: 'Kufri Chandramukhi',
    avgPricePerKg: 18.0,
    traditionalRetailPricePerKg: 24.0,
    priceTrendPct: 0.5,
    trendDirection: 'stable',
    demandLevel: 'MEDIUM',
    supplyLevel: 'SURPLUS',
    dominantDistrict: 'Noida & Meerut',
    anomalyDetected: false,
    lastUpdated: '02 Sep 2026, 17:30 IST',
  },
  {
    id: 'mp-onion',
    product: 'Onion',
    category: 'Vegetables',
    variety: 'Nashik Red A-Grade',
    avgPricePerKg: 27.0,
    traditionalRetailPricePerKg: 38.0,
    priceTrendPct: -4.2,
    trendDirection: 'down',
    demandLevel: 'HIGH',
    supplyLevel: 'DEFICIT',
    dominantDistrict: 'Ghaziabad & Delhi',
    anomalyDetected: true,
    anomalyDetails: 'Inter-district retail spread divergence (+16% in Ghaziabad vs Meerut wholesale).',
    lastUpdated: '02 Sep 2026, 17:50 IST',
  },
  {
    id: 'mp-carrot',
    product: 'Carrot (Gajar)',
    category: 'Vegetables',
    variety: 'Pusa Kesar Red',
    avgPricePerKg: 31.0,
    traditionalRetailPricePerKg: 42.0,
    priceTrendPct: 3.1,
    trendDirection: 'up',
    demandLevel: 'LOW',
    supplyLevel: 'ADEQUATE',
    dominantDistrict: 'Ghaziabad & Faridabad',
    anomalyDetected: false,
    lastUpdated: '02 Sep 2026, 16:40 IST',
  },
  {
    id: 'mp-cauliflower',
    product: 'Cauliflower',
    category: 'Vegetables',
    variety: 'Early Kunwari Snowball',
    avgPricePerKg: 23.5,
    traditionalRetailPricePerKg: 30.0,
    priceTrendPct: 2.8,
    trendDirection: 'up',
    demandLevel: 'MEDIUM',
    supplyLevel: 'ADEQUATE',
    dominantDistrict: 'Noida & Delhi',
    anomalyDetected: false,
    lastUpdated: '02 Sep 2026, 17:15 IST',
  },
  {
    id: 'mp-paddy',
    product: 'Basmati Paddy',
    category: 'Grains',
    variety: 'Pusa 1121 Export',
    avgPricePerKg: 84.0,
    traditionalRetailPricePerKg: 96.0,
    priceTrendPct: 4.0,
    trendDirection: 'up',
    demandLevel: 'HIGH',
    supplyLevel: 'ADEQUATE',
    dominantDistrict: 'Meerut & Sonipat',
    anomalyDetected: false,
    lastUpdated: '02 Sep 2026, 15:20 IST',
  },
  {
    id: 'mp-wheat',
    product: 'Sharbati Wheat',
    category: 'Grains',
    variety: 'PBW 343 Milling Grade',
    avgPricePerKg: 32.0,
    traditionalRetailPricePerKg: 38.0,
    priceTrendPct: 1.2,
    trendDirection: 'stable',
    demandLevel: 'MEDIUM',
    supplyLevel: 'ADEQUATE',
    dominantDistrict: 'Meerut & Sonipat',
    anomalyDetected: false,
    lastUpdated: '02 Sep 2026, 16:05 IST',
  },
];

export const GOVERNMENT_ALERTS: GovernmentSecurityAlert[] = [
  {
    id: 'alt-01',
    alertType: 'HIGH_DEMAND',
    title: 'High Demand Surge: Delhi Tomato Cluster',
    description: 'Tomato demand in Delhi urban retail centers increased by 21.0% within the last 24 hours. Inventory buffer at 1.4 days.',
    severity: 'CRITICAL',
    timestamp: '18 mins ago',
    entityAffected: 'Delhi NCT (Okhla & Azadpur Intake)',
    recommendedAction: 'Trigger automated green corridor routing for 180 tonnes from Noida and Sonipat cold-chain reserves.',
    status: 'ACTIVE',
  },
  {
    id: 'alt-02',
    alertType: 'SUPPLY_SURPLUS',
    title: 'Supply Surplus Alert: Noida Potato Harvest',
    description: 'Potato supply in Noida aggregator depots is 18.0% above active buyer demand, risking storage degradation.',
    severity: 'HIGH',
    timestamp: '42 mins ago',
    entityAffected: 'Noida Sector 63 Packhouse Hub',
    recommendedAction: 'Facilitate B2B institutional procurement contracts with Delhi processing consortia.',
    status: 'ACTIVE',
  },
  {
    id: 'alt-03',
    alertType: 'PRICE_ANOMALY',
    title: 'Price Anomaly: Onion Variance in Ghaziabad',
    description: 'Onion prices in Ghaziabad changed by 16.0% despite stable regional mandi arrivals, indicating retail cartel hoarding.',
    severity: 'HIGH',
    timestamp: '1 hour ago',
    entityAffected: 'Ghaziabad Sub-Mandi Sector',
    recommendedAction: 'Dispatch district enforcement inspection teams and release 40 tonnes buffer stock at MSP baseline.',
    status: 'INVESTIGATING',
  },
  {
    id: 'alt-04',
    alertType: 'SECURITY_ALERT',
    title: 'Cyber Security Alert: Unusual Transaction Velocity Detected',
    description: 'Unusual rapid micro-transaction burst (42 transactions/min from single corporate proxy IP) flagged by autonomous AI risk engine.',
    severity: 'CRITICAL',
    timestamp: '2 hours ago',
    entityAffected: 'Payment Gateway Escrow Node #3',
    recommendedAction: 'Rate-limiting triggered automatically; accounts isolated for multi-factor cryptographic audit.',
    status: 'INVESTIGATING',
  },
];

export const TRANSACTION_SECURITY_STATS: TransactionSecurityStats = {
  totalTransactions: 48293,
  verifiedTransactions: 47812,
  flaggedTransactions: 481,
  fraudRiskAlerts: 37,
  suspiciousVolumeAlerts: 14,
  failedPaymentSurges: 9,
  abnormalPriceShifts: 8,
  unusualAccountActivity: 6,
};

export const FRAUD_FLAG_RECORDS: FraudFlagRecord[] = [
  {
    id: 'fr-01',
    txId: 'TX-10942',
    buyerOrFarmer: 'Buyer #B492 (Wholesale Corp)',
    amount: 148000,
    riskScore: 'HIGH',
    reason: 'Rapid velocity (6 transactions within 90s) & abnormal unit pricing (₹8/kg for Grade A tomato vs ₹22 market).',
    timestamp: '02 Sep 2026, 17:24',
    investigationStatus: 'UNDER_REVIEW',
  },
  {
    id: 'fr-02',
    txId: 'TX-10884',
    buyerOrFarmer: 'Entity #E712 (Unverified Geo)',
    amount: 92400,
    riskScore: 'HIGH',
    reason: 'Multiple failed UPI 2FA tokens followed by sudden credential modification from disparate ASN.',
    timestamp: '02 Sep 2026, 16:50',
    investigationStatus: 'ESCALATED',
  },
  {
    id: 'fr-03',
    txId: 'TX-10765',
    buyerOrFarmer: 'Buyer #B319 (Retail Chain)',
    amount: 38500,
    riskScore: 'MEDIUM',
    reason: 'Volume spike 400% above 30-day baseline during non-operational mandi hours.',
    timestamp: '02 Sep 2026, 15:10',
    investigationStatus: 'UNDER_REVIEW',
  },
  {
    id: 'fr-04',
    txId: 'TX-10610',
    buyerOrFarmer: 'Farmer Collective #F104',
    amount: 64200,
    riskScore: 'LOW',
    reason: 'Minor weighbridge metadata discrepancy (0.8% weight mismatch vs gate entry scan).',
    timestamp: '02 Sep 2026, 13:42',
    investigationStatus: 'CLEARED',
  },
];

export const TRANSACTION_AUDIT_LEDGER: TransactionAuditRecord[] = [
  {
    txId: 'TX-10243',
    orderRef: 'ORD-89421',
    action: 'Payment Completed',
    user: 'Buyer #B381',
    userRole: 'Buyer',
    commodity: 'Tomatoes (Roma A+)',
    quantityKg: 5000,
    totalAmount: 110000,
    farmerPayout: 93500,
    timestamp: '02 Sep 2026, 18:42:15 IST',
    status: 'VERIFIED',
    auditRecordStatus: 'SECURE',
    sha256Hash: '0x8f4c2e19a4b8d7301c2789ef45a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4',
    signerPublicKey: 'gov_auth_root_pubkey_delhi_pune_0x4492',
    otpVerified: true,
  },
  {
    txId: 'TX-10242',
    orderRef: 'ORD-89420',
    action: 'Cold Escrow Settled',
    user: 'Farmer #F892 (Kisan Collective Noida)',
    userRole: 'Farmer',
    commodity: 'Potatoes (Kufri Chandramukhi)',
    quantityKg: 8500,
    totalAmount: 153000,
    farmerPayout: 128520,
    timestamp: '02 Sep 2026, 18:31:04 IST',
    status: 'VERIFIED',
    auditRecordStatus: 'SECURE',
    sha256Hash: '0x7a3b9f10c4d8e2501a3967bc34e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3',
    signerPublicKey: 'gov_auth_root_pubkey_up_noida_0x7812',
    otpVerified: true,
  },
  {
    txId: 'TX-10241',
    orderRef: 'ORD-89419',
    action: 'Logistics Release Sign-off',
    user: 'Carrier #L209 (Green Express Fleet)',
    userRole: 'Logistics',
    commodity: 'Nashik Red Onions',
    quantityKg: 4200,
    totalAmount: 113400,
    farmerPayout: 97524,
    timestamp: '02 Sep 2026, 18:14:50 IST',
    status: 'VERIFIED',
    auditRecordStatus: 'TAMPER_EVIDENT',
    sha256Hash: '0x6e2a8c09b3d7f1402b4856cd23d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2',
    signerPublicKey: 'gov_auth_root_pubkey_ghaziabad_0x9921',
    otpVerified: true,
  },
  {
    txId: 'TX-10240',
    orderRef: 'ORD-89418',
    action: 'Produce Quality Certification',
    user: 'FPO Admin #A118 (Sonipat Cluster)',
    userRole: 'FPO Admin',
    commodity: 'Hydroponic Mushroom & Baby Corn',
    quantityKg: 1800,
    totalAmount: 152000,
    farmerPayout: 130720,
    timestamp: '02 Sep 2026, 17:58:22 IST',
    status: 'VERIFIED',
    auditRecordStatus: 'SECURE',
    sha256Hash: '0x5d197b08a2c6e0301a3745bc12c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1',
    signerPublicKey: 'gov_auth_root_pubkey_sonipat_0x3344',
    otpVerified: true,
  },
];

export const GOVERNMENT_REPORTS: ReportConfig[] = [
  {
    id: 'rep-01',
    title: 'National Farmer Participation & Income Realization Report',
    description: 'Comprehensive quarterly assessment of 12,482 onboarded farmers, direct payout spreads, and intermediaries eliminated.',
    category: 'Farmers',
    generatedAt: '02 Sep 2026, 06:00 IST',
    size: '4.8 MB',
    recordCount: 12482,
  },
  {
    id: 'rep-02',
    title: 'Inter-District Produce Movement & Cold-Chain Logistics Audit',
    description: 'Flow analysis of 1,284 tonnes across Delhi NCR, bottleneck incident log, transit costs, and freshness index.',
    category: 'Logistics',
    generatedAt: '02 Sep 2026, 12:00 IST',
    size: '6.2 MB',
    recordCount: 3410,
  },
  {
    id: 'rep-03',
    title: 'Mandi Price Parity & Consumer Inflation Moderation Report',
    description: 'Detailed analysis of 9.2% consumer price moderation vs 18.4% farmer income uplift across 14 major crops.',
    category: 'Pricing',
    generatedAt: '02 Sep 2026, 14:30 IST',
    size: '3.1 MB',
    recordCount: 8940,
  },
  {
    id: 'rep-04',
    title: 'Supply-Demand Hotspot & Buffer Stock Policy Whitepaper',
    description: 'Predictive modeling on tomato, onion, and potato shortages in urban zones with actionable redirection directives.',
    category: 'Supply & Demand',
    generatedAt: '02 Sep 2026, 16:00 IST',
    size: '5.5 MB',
    recordCount: 1420,
  },
  {
    id: 'rep-05',
    title: 'Cryptographic Transaction Ledger & Anti-Fraud Security Audit',
    description: 'Immutable ledger proof with SHA-256 block chain verification, 48,293 transactions audit trail, and risk flags analysis.',
    category: 'Security & Audit',
    generatedAt: '02 Sep 2026, 18:00 IST',
    size: '12.4 MB',
    recordCount: 48293,
  },
];

export const KEY_GOVERNMENT_INSIGHTS = [
  {
    id: 'ins-1',
    title: 'Tomato demand in Delhi is increasing rapidly.',
    description: 'Urban consumption spikes have driven a 21.0% demand surge over the last 48 hours, creating regional supply tension.',
    tag: 'Demand Shift',
    impactScore: 'High Impact',
  },
  {
    id: 'ins-2',
    title: 'Noida currently has surplus tomato supply.',
    description: 'Noida FPO packhouses currently hold 340 tonnes with harvest arrival rate outstripping local buyer capacity by 18.0%.',
    tag: 'Surplus Opportunity',
    impactScore: 'Immediate Arbitrage',
  },
  {
    id: 'ins-3',
    title: 'Direct transactions have increased average farmer earnings by 18.4%.',
    description: 'Smallholder farmers earn ₹10,065 modal realization vs ₹8,500 under traditional APMC middleman structures.',
    tag: 'Farmer Uplift',
    impactScore: 'Policy Goal Achieved',
  },
  {
    id: 'ins-4',
    title: 'Consumer prices are approximately 9.2% lower than traditional retail estimates.',
    description: 'Urban households save ₹3 to ₹4 per kg on daily produce while receiving fresher, harvest-graded commodities.',
    tag: 'Consumer Savings',
    impactScore: 'Inflation Shield',
  },
  {
    id: 'ins-5',
    title: 'Redirecting surplus produce toward high-demand districts could reduce wastage and transportation inefficiencies.',
    description: 'Dynamic green corridor clearance from Noida to Delhi can eliminate 14 tonnes of post-harvest spoilage daily.',
    tag: 'Logistics Optimization',
    impactScore: 'Actionable Directive',
  },
];
